# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

log_mat <- function(R) {
    .Call(`_gcr_log_mat`, R)
}

exp_mat <- function(R) {
    .Call(`_gcr_exp_mat`, R)
}

exp_solve_mat <- function(R) {
    .Call(`_gcr_exp_solve_mat`, R)
}

exp_sqrt_solve_mat <- function(R) {
    .Call(`_gcr_exp_sqrt_solve_mat`, R)
}

generate_J <- function(R_solve) {
    .Call(`_gcr_generate_J`, R_solve)
}

generate_J_extra <- function(R_solve, R_sqrt_solve, a_d4, a_d2, phi) {
    .Call(`_gcr_generate_J_extra`, R_solve, R_sqrt_solve, a_d4, a_d2, phi)
}

generate_Mid <- function(lambda) {
    .Call(`_gcr_generate_Mid`, lambda)
}

